const ENV_CONFIG = {
  DATABASE_URL: Bun.env.DATABASE_URL,
  PORT: Bun.env.PORT,
  JWT_SECRET: Bun.env.JWT_SECRET || "",
  JWT_ACCESS_TOKEN_EXPIRY: Bun.env.JWT_ACCESS_TOKEN_EXPIRY,
  JWT_REFRESH_TOKEN_EXPIRY: Bun.env.JWT_REFRESH_TOKEN_EXPIRY
}

export default ENV_CONFIG;